{ config, pkgs, ... }:
let
  homeDir = config.home.homeDirectory;
in
{
  programs.mangohud = {
    enable = true;

    # Optional: makes MangoHud start for apps that support it (you still have "no_display"
    # in the config, so it will start hidden until your toggle key).
    enableSessionWide = true;
  };

  # Optional (for editing MangoHud config via GUI like you did on Arch)
  home.packages = with pkgs; [
    goverlay
  ];

  xdg.configFile."MangoHud/MangoHud.conf".text = ''
    ################### File Generated by Goverlay ###################
    legacy_layout=false


    background_alpha=0.4
    round_corners=10
    background_alpha=0.4
    background_color=000000

    font_size=18
    text_color=FFFFFF
    position=top-left
    toggle_hud=Shift_R+F1
    no_display
    pci_dev=0:03:00.0
    table_columns=3
    gpu_text=GPU
    gpu_stats
    gpu_load_change
    gpu_load_value=50,90
    gpu_load_color=FFFFFF,FFAA7F,CC0000
    gpu_core_clock
    gpu_mem_clock
    gpu_temp
    gpu_power
    gpu_color=2E9762
    cpu_text=CPU
    cpu_stats

    cpu_load_change
    cpu_load_value=50,90
    cpu_load_color=FFFFFF,FFAA7F,CC0000
    cpu_mhz
    cpu_temp
    cpu_power
    cpu_color=2E97CB
    vram
    vram_color=AD64C1
    vram_color=AD64C1
    ram
    ram_color=C26693
    fps
    fps_metrics=avg,0.01
    gpu_name
    frame_timing
    frametime_color=FFFFFF
    fps_limit_method=late
    toggle_fps_limit=Shift_L+F1
    show_fps_limit

    fps_limit=280,120,0
    exec=uname -r
    fps_color_change
    fps_color=B22222,FDFD09,39F900
    fps_value=140,280
    #offset=0

    output_folder=${homeDir}
    log_duration=30
    autostart_log=0
    log_interval=100
    toggle_logging=Shift_L+F2

    blacklist=pamac-manager,lact,ghb,bitwig-studio,ptyxis,yumex
  '';
}

